= Frequently asked questions

== I pasted in a command and it doesn't work

Often, this is the result of not correctly substituting a value. 

A tutorial may have a step like: 

_Enter the following command_

`$ mkdir <my email>`

If you paste that in literally, you will get something like this: 

`-bash: syntax error near unexpected token `newline'`

This is because 

. You pasted in the `$`, which is there to just show you that you are operating at a command line
. You pasted in, literally, `<my account>`, rather than replacing the `<my account>` with YOUR ACTUAL EMAIL ACCOUNT. In this case, you would NOT include the @stthomas.edu; however, this may vary. 

This applies in many cases, such as 

[source,bash]
----
$ git clone <my repo path>
$ curl <Kubernetes node IP>
----
and so forth. 

Some tutorials may not use <>; there is no standard. 

== Offending ECDSA key
If you get an `offending ECDSA key` error, use the suggested removal command.

== Permission denied (publickey)

If you get the error `Permission denied (publickey).`, this probably means that your ssh-agent no longer has the node-user private key added. This easily happens if the Google Cloud Shell goes to sleep and wipes out your session. Check via issuing `ssh-add -l`.

If you get a message to the effect that your agent is not running, type `eval `ssh-agent`` and then `ssh-add -l`.

You should see something like `2048 SHA256:bII5VsQY3fCWXEai0lUeChEYPaagMXun3nB9U2eoUEM /home/betz4871/.ssh/node-user (RSA)`.
If you do not, re-issue the command `ssh-add ~/.ssh/node-user` and re-confirm with `ssh-add -l`.

Offending ECDSA key or Permission denied (publickey)

== Terraform error refreshing state

If you get 

[source,bash]
----
Error refreshing state: state snapshot was created by Terraform v0.12.8, which is newer than current v0.12.2; upgrade to Terraform v0.12.8 or greater to work with this state
----

execute 
`rm -rf terraform.tfstate`
`terraform init`

== Nano garbled

If text is overlapping in nano, hit ctrl-L to redraw. 

I had partial success including 

export TERM=screen

in my .bashrc file, but that only seems to work if I only use page up/down. Scrolling with the arrow key is still a problem. 

Issue: https://github.com/vercel/hyper/issues/3391

== Insufficient Permission in Google Cloud Shell

If you receive an `Insufficient Permission` error in the Google Cloud Shell, you may need to reauthenticate.
Type `gcloud auth login` and follow the resulting steps.

== Project property set to the empty string

If you get:
[source,bash]
----
 The project property is set to the empty string, which is invalid. To set your project, run: $ gcloud config set project PROJECT_ID or to unset it, run: $ gcloud config unset 

----

Follow the suggested command. Your project name is visible in the Google Cloud Shell, top right usually under "My First Project." When you find it, issue the command

[source,bash]
----
gcloud config set project MY PROJECT NAME
Updated property [core/project].prkjnghn@cloudshell:~ 
----

Obviously, you change MY PROJECT NAME to your actual project.

== API not enabled

If you receive

[source,bash]
----
API [compute.googleapis.com] not enabled on project [389601984173].Would you like to enable and retry (this will take a few minutes)?(y/N)?  
----

Hit `y`, you should get:

`Enabling service [compute.googleapis.com] on project [389601984173]...`

== Address already in use

When starting up the nodejs server with `nodejs server.js &` you may encounter a `address already in use` error. Read carefully, as this output may be further down in the error output. This indicates that there is already a node server running. If you would like to start over, run `ps -ef` to list processes and then kill the correct process by id: `kill {process id}`

== Switching Github remote from http (cleartext password) to ssh
See https://docs.github.com/en/github/using-git/changing-a-remotes-url[this link.]