= Frequently asked questions

== Offending ECDSA key
If you get an `offending ECDSA key` error, use the suggested removal command.

== Permission denied (publickey)

If you get the error `Permission denied (publickey).`, this probably means that your ssh-agent no longer has the node-user private key added. This easily happens if the Google Cloud Shell goes to sleep and wipes out your session. Check via issuing `ssh-add -l`.

If you get a message to the effect that your agent is not running, type `eval `ssh-agent`` and then `ssh-add -l`.

You should see something like `2048 SHA256:bII5VsQY3fCWXEai0lUeChEYPaagMXun3nB9U2eoUEM /home/betz4871/.ssh/node-user (RSA)`.
If you do not, re-issue the command `ssh-add ~/.ssh/node-user` and re-confirm with `ssh-add -l`.

Offending ECDSA key or Permission denied (publickey)

== Terraform error refreshing state  
Thank you

If you get 

....
Error refreshing state: state snapshot was created by Terraform v0.12.8, which is newer than current v0.12.2; upgrade to Terraform v0.12.8 or greater to work with this state
....

execute 
`rm -rf terraform.tfstate`
`terraform init`

== Nano garbled

If text is overlapping in nano, hit ctrl-L to redraw. 

I had partial success including 

export TERM=screen

in my .bashrc file, but that only seems to work if I only use page up/down. Scrolling with the arrow key is still a problem. 

Issue: https://github.com/vercel/hyper/issues/3391
