= Lab 04 Product management

==  Overview

- Upping our Git collaboration

Important: To continue with Git, you MUST have ssh configured. If you are still typing in a username and password, you must go back to lab 00 and complete the ssh section. 

Up until now, we have been somewhat haphazard and basic with our usage of git and Github, just as a startup with a couple of individuals might be -- primarily using it as a repository/archive, but not very effectively as a collaboration tool. 

In particular we have been using this basic approach: 

(graphic)

There are two problems with this approach: 

1. We have to go to the Github GUI to issue a pull request, which breaks flow from our command line work. 
2. There is no convenient way to pull updates from upstream into our local repo. 

There are two ways we can solve this. 

1. I could make you all members of my Github project. This is too much administration for me every semester. 
2. We can continue to have you fork and then clone (as you would if you were participating in an open source project for which you were not yet a committer) but set things up so that you can do it all from the command line. 

We will go with option #2. 

In order to proceed with #2, we need to better understand the concept of a git "remote." Git is a powerful tool for distributed collaboration on complex software projects, and therefore itself is complex. 

According to https://www.git-tower.com/, "A remote in Git is a common repository that all team members use to exchange their changes. In most cases, such a remote repository is stored on a code hosting service like GitHub or on an internal server."

What this does not mention is that a git repository can have _multiple_ remotes. Your local clone on the Google Cloud Shell has, as a remote, the fork you created in Github. This is its origin.  Now, you are going to set as your _upstream_ remote the original source repository you cloned from as a template. 

(This lab is based on these instructions: https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/configuring-a-remote-for-a-fork.)



One of the major focuses of this lab will be to 

- Taking a break from the technicalities
-- (You can catch up now)
- Take stock of the product and its needs
- Documenting a vision
- Develop a backlog
- Hypothesis testing
- Feature flags?
