:linkattrs:

= Lab 03 Docker, Kubernetes, and your first CD pipeline

Check out branch master: 

[source,bash]
----
$ git checkout master
----

Notice how some files disappear. That's right, we won't be using Ansible or Packer any more.

== Docker

In this section, we will talk about managing containers for the first time in this tutorial.
Particularly, we will talk about https://www.docker.com/what-docker[Docker] which is the most widely used platform for running containers.

NOTE: For this section we will just run the container on the Google Cloud Shell, which can run containers locally. No VMs!

=== Intro

Remember when we talked about packer, we mentioned a few words about *Immutable Infrastructure* model? The idea was to package all application dependencies and application itself inside a machine image, so that we don't have to configure the system after start.
Containers implement the same model, but they do it in a more efficient way.

Containers allow you to create self-contained isolated environments for running your applications.

They have some significant advantages over VMs in terms of implementing Immutable Infrastructure model:

* *Containers are much faster to start than VMs.* Container starts in seconds, while a VM takes minutes. It's important when you're doing an update/rollback or scaling your service.
* *Containers enable better utilization of compute resources.* Very often computer resources of a VM running an application are underutilized. Launching multiple instances of the same application on one VM has a lot of difficulties: different application versions may need different versions of dependent libraries, init scripts require special configuration. With containers, running multiple instances of the same application on the same machine is easy and doesn't require any system configuration.
* *Containers are more lightweight than VMs.* Container images are much smaller than machine images, because they don't need a full operating system in order to run. In fact, a container image can include just a single binary and take just a few MBs of your disk space. This means that we need less space for storing the images and the process of distributing images goes faster.

Let's try to implement *Immutable Infrastructure* model with Docker containers, while paying special attention to the *Dockerfile* part as a way to practice *Infrastructure as Code* approach.

=== The Dockerfile
Open and review the file called Dockerfile in the node-svc master branch. 

You describe a container image that you want to create in a special file called *Dockerfile*.

Dockerfile contains *instructions* on how the image should be built. Here are some of the most common instructions that you can meet in a Dockerfile:

* `FROM` is used to specify a *base image* for this build.
It's similar to the builder configuration which we defined in a Packer template, but in this case instead of describing characteristics of a VM, we simply specify a name of a container image used for build.
This should be the first instruction in the Dockerfile.
* `ADD` and `COPY` are used to copy a file/directory to the container.
See the https://stackoverflow.com/questions/24958140/what-is-the-difference-between-the-copy-and-add-commands-in-a-dockerfile[difference] between the two.
* `RUN` is used to run a command inside the image.
Mostly used for installing packages.
* `ENV` sets an environment variable available within the container.
* `WORKDIR` changes the working directory of the container to a specified path.
It basically works like a `cd` command on Linux.
* `CMD` sets a default command, which will be executed when a container starts.
This should be a command to start your application.

See how these instructions are used in the Dockerfile in your to create a Docker container image for our node-svc application.

This Dockerfile repeats the steps that we did multiple times by now to configure a running environment for our application and run it.

We first choose an image that already contains Node of required version:

----
# Use base image with node installed
FROM node:11
----

The base image is downloaded from Docker official registry (storage of images) called https://hub.docker.com/[Docker Hub].

We then install required system packages and application dependencies:

----
# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)COPY package*.json ./
RUN npm install
RUN npm install express
----

Then we copy the application itself.

----
# create application home directory and copy files
COPY . /app
----

Then we specify a default command that should be run when a container from this image starts:

----
CMD [ "node", "server.js" ]
----

=== Build Container Image

Once you defined how your image should be built, run the following command inside your `my-iac-tutorial` directory to create a container image for the node-svc application:

[source,bash]
----
$ docker build -t <yourGoogleID>/node-svc-v1 .
----

The resulting image will be named `node-svc-v1`.
Find it in the list of your local images:

[source,bash]
----
$ docker images | grep node-svc-v1
----

At your option, you can save your build command in a script, such as `build.sh`.

Now, run the container:

[source,bash]
----
docker run -d -p 8081:30100 level-research-289323/node-svc-v1
----

Notice the "8081:3000" syntax.
This means that while the container is running on port 3000 internally, it is externally exposed via port 8081.

Again, you may wish to save this in a script, such as `run.sh`.

Now, test the container:

[source,bash]
----
$ curl localhost:8081
{"action":"GET","arrTimeStamp":["172.18.0.1 Sun Sep 06 2020 20:32:50 GMT+0000 (Coordinated Universal Time)"]}
----

Again, you may wish to save this in a script, such as `test.sh`.

=== Save and commit the work

Save and commit the files created in this section.

=== Conclusion

In this section, you adopted containers for running your application. This is a different type of technology from what we used to deal with in the previous sections. Nevertheless, we use Infrastructure as Code approach here, too.

We describe the configuration of our container image in a Dockerfile using Dockerfile's syntax. We then save that Dockerfile in our application repository. This way we can build the application image consistently across any environments.

Destroy the current playground before moving on to the next section, through `docker ps`, `docker kill`, `docker images`, and `docker rmi`. In the example below, the container is named "beautiful_pascal". Yours will be different. Follow the example, substituting yours.

[source,bash]
----
$ docker ps
CONTAINER ID        IMAGE                      COMMAND                  CREATED             STATUS              PORTS                    NAMES
64e60b7b0c81        charlestbetz/node-svc-v1   "docker-entrypoint.s…"   10 minutes ago      Up 10 minutes       0.0.0.0:8081->3000/tcp   beautiful_pascal
$ docker kill beautiful_pascal
$ docker images
# returns list of your images
$ docker rmi <one or more image names> -f
----

== Kubernetes

In the previous section, we learned how to run Docker containers locally. Running containers at scale is quite different and a special class of tools, known as *orchestrators*, are used for that task.

In this section, we'll take a look at the most popular Open Source orchestration platform called https://kubernetes.io/[Kubernetes] and see how it implements Infrastructure as Code model.

=== Intro

We used Docker to consistently create container infrastructure on one machine (our local machine). However, our production environment may include tens or hundreds of VMs to have enough capacity to provide service to a large number of users. What do you do in that case?

Questions arise as to:

* how to load balance containerized applications?
* how to perform container health checks and ensure the required number of containers is running?
* how can containers communicate securely?

The world of containers is very different from the world of virtual machines and needs a special platform for management.

Kubernetes is the most widely used orchestration platform for running and managing containers at scale.
It solves the common problems (some of which we've mentioned above) related to running containers on multiple hosts. And we'll see in this section that it uses the Infrastructure as Code approach to managing container infrastructure.

Let's try to run our `node-svc` application on a Kubernetes cluster.

=== TEMPORARY
As of fall 2020, the Google Cloud Shell versions of Terraform and the Google Cloud Provisioner are out of date. You need to install a local version of Terraform and always call it explicitly. Inspect and run: 

[source,bash]
----
$ update-terraform.sh
----

This installs Terraform 13 in your local ~/bin directory. 

See the difference: 

[source,bash]
----
$ terraform -v # Google's version
Terraform v0.12.24
+ provider.google v2.5.1
Your version of Terraform is out of date! The latest version
is 0.13.2. You can update by downloading from https://www.terraform.io/downloads.html
betz4871:node-svc$ ~/bin/terraform -v

$ ~/terraform -v # your version
  Terraform v0.13.2
+ provider registry.terraform.io/hashicorp/google v3.37.0
----

You need to ALWAYS call Terraform thus: 

[source,bash]
----
$ ~/bin/terraform apply
----

Terraform will CRASH HARD if you do not do this.

=== Describe Kubernetes cluster in Terraform

We'll use https://cloud.google.com/kubernetes-engine/[Google Kubernetes Engine] (GKE) service to deploy a Kubernetes cluster of 3 nodes.

We'll describe a Kubernetes cluster using Terraform so that we can manage it through code.

Review these three files, which have changed since Lab 02:

[source,bash]
----
variables.tf
terraform.tfvars
main.tf
----

We'll use this Terraform code to create a Kubernetes cluster.

=== Create Kubernetes Cluster

`main.tf` holds all the information about the cluster that should be created.
It's parameterized using Terraform https://www.terraform.io/intro/getting-started/variables.html[input variables] which allow you to easily change configuration parameters.

Look into `terraform.tfvars` file which contains definitions of the input variables and change them if necessary. You must change the `project_id` value.

After you've corrected the variables, run Terraform to create a Kubernetes cluster consisting of 3 nodes (VMs for running our application containers). (You should know the command by now.)

[source,bash]
----
$ gcloud services enable container.googleapis.com # enable Kubernetes Engine API
$ ~/bin/terraform init
$ ~/bin/terraform apply
----

Wait until Terraform finishes creation of the cluster. It can take about 3-5 minutes.

Check that the cluster is running and `kubectl` is properly configured to communicate with it by fetching cluster information:

[source,bash]
----
$ kubectl cluster-info

Kubernetes master is running at https://104.197.22.1
GLBCDefaultBackend is running at https://104.197.22.1/api/v1/namespaces/kube-system/services/default-http-backend:http/proxy
[...]
----

=== Deployment manifest

Kubernetes implements Infrastructure as Code approach to managing container infrastructure.
It uses special entities called *objects* to represent the `desired state` of your cluster.
With objects you can describe

* What containerized applications are running (and on which nodes)
* The compute resources available to those applications
* The policies around how those applications behave, such as restart policies, upgrades, and fault-tolerance

By creating an object, you're effectively telling the Kubernetes system what you want your cluster's workload to look like;
this is your cluster's *desired state*.
Kubernetes then makes sure that the cluster's actual state meets the desired state described in the object.

Most of the times, you describe the object in a `.yaml` file called `manifest` and then give it to `kubectl` which in turn is responsible for relaying that information to Kubernetes via its API.

*Deployment object* represents an application running on your cluster.
We'll use it to run containers of our applications.

Review the `deployments.yaml` file. 

In this file we describe two `Deployment objects` which define what application containers and in what quantity should be run.
The Deployment objects have the same structure so I'll briefly go over only one of them.

Each Kubernetes object has 4 required fields:

* `apiVersion` - Which version of the Kubernetes API you're using to create this object. You'll need to change that if you're using Kubernetes API version different than 1.7 as in this example.
* `kind` - What kind of object you want to create. In this case we create a Deployment object.
* `metadata` - Data that helps uniquely identify the object. In this example, we give the deployment object a name according to the name of an application it's used to run.
* `spec` - describes the `desired state` for the object. `Spec` configuration will differ from object to object, because different objects are used for different purposes.

In the Deployment object's spec we specify, how many `replicas` (instances of the same application) we want to run and what those applications are (`selector`)

[source,yml]
----
spec:
  replicas: 5
  selector:
    matchlabels:
      app: node-svc
----

In our case, we specify that we want to be running 5 instances of applications that have a lable `app=node-svc`.
*labels* are used to give identifying attributes to Kubernetes objects and can be then used by *label selectors* for objects selection.

We also specify a `Pod template` in the spec configuration. *Pods* are lower level objects than Deployments and are used to run only `a single instance of application`.
In most cases, Pod is equal to a container, although you can run multiple containers in a single Pod.

The `Pod template` which is a Pod object's definition nested inside the Deployment object.
It has the required object fields such as `metadata` and `spec`, but it doesn't have `apiVersion` and `kind` fields as those would be redundant in this case.
When we create a Deployment object, the Pod object(s) will be created as well. The number of Pods will be equal to the number of `replicas` specified. The Deployment object ensures that the right number of Pods (`replicas`) is always running.

In the Pod object definition (`Pod template`) we specify container information such as a container image name, a container name, which is used by Kubernetes to run the application.
We also add labels to identify what application this Pod object is used to run, this label value is then used by the `selector` field in the Deployment object to select the right Pod object.

[source,yaml]
----
  template:
    metadata:
      labels:
        app: node-svc
    spec:
      containers:
      - name: node-svc
        image: dmacademy/node-svc
----

The container image will be downloaded from https://hub.docker.com/[Docker Hub] in this case: the node-svc image uploaded to the dmacademy organization. We could also use the https://cloud.google.com/container-registry/[Google Container Registry] or https://github.com/features/packages[Github Packages].

=== Create Deployment Objects

Run a kubectl command to create Deployment objects inside your Kubernetes cluster (make sure to provide the correct path to the manifest file):

[source,bash]
----
$ kubectl apply -f deployments.yaml
----

Check the deployments and pods that have been created:

[source,bash]
----
$ kubectl get deploy
$ kubectl get pods
----

=== Service manifests

Running applications at scale means running _multiple containers spread across multiple VMs_. This gives rise to questions such as: 

* How do we load balance between all of these application containers?
* How do we provide a single entry point for the application so that we could connect to it via that entry point instead of connecting to a particular container?

These questions are addressed by the *Service* object in Kubernetes. A Service is an abstraction which you can use to logically group containers (Pods) running in you cluster, that all provide the same functionality.

When a Service object is created, it is assigned a unique IP address called `clusterIP` (a single entry point for our application). Other Pods can then be configured to talk to the Service, and the Service will load balance the requests to containers (Pods) that are members of that Service.

So we create a Service for the node-svc applications.

Review the file called `services.yaml` inside `kubernetes/manifests` directory with the following content:

[source,yaml]
----
apiVersion: v1
kind: Service
metadata:
  name: node-svc-public
spec:
  type: NodePort
  selector:
    app: node-svc
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 30100
----

In this manifest, we describe the node-svc object.

You should be already familiar with the general object structure, so I'll just go over the `spec` field which defines the desired state of the object.

The `node-svc` Service has a NodePort type:

[source,yaml]
----
spec:
  type: NodePort
----

This type of Service makes the Service accessible on each Node's IP at a static port (NodePort). We use this type to be able to contact the `node-svc` application later from outside the cluster.

`selector` field is used to identify a set of Pods to which to route packets that the Service receives.
In this case, Pods that have a label `app=node-svc` will become part of this Service.

[source,yaml]
----
  selector:
    app: node-svc
----

The `ports` section specifies the port mapping between a Service and Pods that are part of this Service and also contains definition of a node port number (`nodePort`) which we will use to reach the Service from outside the cluster.

[source,yaml]
----
  ports:
  - protocol: TCP
    port: 9292
    targetPort: 9292
    nodePort: 30100
----

The requests that come to any of your cluster nodes' public IP addresses on the specified `nodePort` will be routed to the `node-svc` Service cluster-internal IP address.
The Service, which is listening on port 9292 (`port`) and is accessible within the cluster on this port, will then route the packets to the `targetPort` on one of the Pods which is part of this Service.

=== Create Service Objects

Run a kubectl command to create Service objects inside your Kubernetes cluster (make sure to provide the correct path to the manifest file):

[source,bash]
----
$ kubectl apply -f services.yaml
----

Check that the services have been created:

[source,bash]
----
$ kubectl get svc
----

=== Access Application

Because we used `NodePort` type of service for the `node-svc` service, our application should accessible to us on the IP address of any of our cluster nodes.

NOTE: It may take up to 3 minutes for Kubernetes to launch your containers.   

Get a list of IP addresses of your cluster nodes:

[source,bash]
----
$ gcloud --format="value(networkInterfaces[0].accessConfigs[0].natIP)" compute instances list --filter="tags.items=node-svc-k8s"
----

Use any of your nodes public IP addresses and the node port `30100` which we specified in the service object definition to reach the `node-svc` application in your browser. Just try the main address (no /).

Or, if you like, just issue the appropriate curl command. 

Take a screenshot of the results and submit to the lab assignment. 

=== Save and commit the work

Save and commit the `kubernetes` folder created in this section into your `iac-tutorial` repo. If you are going to take a break, you probably should destroy your Kubernetes cluster. 

=== Conclusion

In this section, we learned about Kuberenetes - a popular orchestration platform which simplifies the process of running containers at scale. We saw how it implements the Infrastructure as Code approach in the form of `objects` and `manifests` which allow you to describe in code the desired state of your container infrastructure which spans a cluster of VMs.


== Updating the service: towards a true pipeline

In the last section, we were able to access the application's main URL. Also, at this point /0  is working .... but /1, /3, /30 etc are not. We need to: 

* figure out what's wrong
* update server.js
* test it locally (either directly or as a container)
* rebuild the container
* push it to the Docker Hub
* tell Kubernetes to re-apply the deployment. 

You'll quickly realize this is a set of often repeated actions. We're now ready for continuous delivery (to be continued...)

Next up: 

* Break/fix analysis
* Code commenting
* Automated testing
* Mutiple environments
* Continuous delivery pipeline
* Collaboration using Github

=== Break/fix analysis
It's one thing to fix code that you're developing on your workstation. It's another thing entirely to fix code that is breaking in production. In this case, you have a service that worked fine on both VMs and Docker, but is ony partially functional in Kubernetes. 

The first question you should always ask in this situation: what do the logs say? 

First, what is a log? It is a record of what the system is doing. Remember stdout and stderr from your Unix tutorial? (Review them if you don't.) These output streams are usually being monitored and recorded when software is deployed and started in a running system. Kubernetes is no exception. 

The simplest way to get Kubernetes logs is as follows. First, get all your pod IDs: 

[source,bash]
----
get pods --all-namespaces
NAMESPACE     NAME                                                        READY   STATUS              RESTARTS   AGE
default       node-svc-deployment-cf76549ff-9cdxr                         1/1     Running             0          3m11s
default       node-svc-deployment-cf76549ff-d5rnq                         1/1     Running             0          3m11s
default       node-svc-deployment-cf76549ff-d9hq9                         0/1     ContainerCreating   0          3m11s
default       node-svc-deployment-cf76549ff-s5vwf                         1/1     Running             0          3m11s
default       node-svc-deployment-cf76549ff-w6chl                         1/1     Running             0          3m11s
kube-system   event-exporter-v0.3.0-5cd6ccb7f7-l9lqc                      2/2     Running             0          70m
kube-system   fluentd-gcp-scaler-6855f55bcc-kwd8l                         1/1     Running             0          70m
kube-system   fluentd-gcp-v3.1.1-4qlhp                                    2/2     Running             0          70m
kube-system   fluentd-gcp-v3.1.1-bhrhr                                    2/2     Running             0          70m
kube-system   fluentd-gcp-v3.1.1-xhqs7                                    2/2     Running             0          70m
kube-system   heapster-gke-5d76c889bb-wr8j6                               3/3     Running             0          69m
kube-system   kube-dns-5c446b66bd-5r479                                   4/4     Running             0          71m
kube-system   kube-dns-5c446b66bd-m7l6d                                   4/4     Running             0          70m
kube-system   kube-dns-autoscaler-6b7f784798-dwk84                        1/1     Running             0          70m
kube-system   kube-proxy-gke-node-svc-k8s-default-pool-53125139-07bt      1/1     Running             0          70m
kube-system   kube-proxy-gke-node-svc-k8s-default-pool-53125139-ctw4      1/1     Running             0          70m
kube-system   kube-proxy-gke-node-svc-k8s-default-pool-53125139-n2t5      1/1     Running             0          70m
kube-system   l7-default-backend-84c9fcfbb-9lpcp                          1/1     Running             0          71m
kube-system   metrics-server-v0.3.3-fdc67d4b6-2p7q9                       2/2     Running             0          70m
kube-system   prometheus-to-sd-76wsg                                      2/2     Running             0          70m
kube-system   prometheus-to-sd-hbdl9                                      2/2     Running             0          70m
kube-system   prometheus-to-sd-xjvfw                                      2/2     Running             0          70m
kube-system   stackdriver-metadata-agent-cluster-level-7bb8c5b7fd-hzz49   2/2     Running             0          69m
----

This is a very important list and you should spend some time looking it over. 

Now, get the log from the first pod: 

[source,bash]
----
kubectl -n default logs node-svc-deployment-cf76549ff-9cdxr
[various output]
Running on 3000
Console: request is testing a simple self-get
Console: request is testing a simple self-post
DateIPStamp reached with {"action":"GET"} 127.0.0.1
Console: / Server returned success on get.
{ action: 'GET',
  arrTimeStamp:
   [ '127.0.0.1 Tue Sep 08 2020 23:48:50 GMT+0000 (Coordinated Universal Time)' ] }
Console: entered / post
Console: / received {"firstName":"myFirstName","lastName":"myLastName"}
DateIPStamp reached with {"firstName":"myFirstName","lastName":"myLastName","action":"POST"} 127.0.0.1
Console: / returned {"firstName":"myFirstName","lastName":"myLastName","action":"POST","arrTimeStamp":["127.0.0.1 Tue Sep 08 2020 23:48:50 GMT+0000 (Coordinated Universal Time)"]}
{ firstName: 'myFirstName',
  lastName: 'myLastName',
  action: 'POST',
  arrTimeStamp:
   [ '127.0.0.1 Tue Sep 08 2020 23:48:50 GMT+0000 (Coordinated Universal Time)' ] }
/n GET, making GET subrequest
returning URL http://node-svc-01:3000/2
(node:1) UnhandledPromiseRejectionWarning: FetchError: request to http://node-svc-01:3000/2 failed, reason: getaddrinfo ENOTFOUND node-svc-01 node-svc-01:3000
    at ClientRequest.<anonymous> (/app/node_modules/node-fetch/lib/index.js:1461:11)
    at ClientRequest.emit (events.js:193:13)
    at Socket.socketErrorListener (_http_client.js:397:9)
    at Socket.emit (events.js:193:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
----

You should see some routine-looking output, and some output that looks more like an error. Discuss with your teammates and/or in class. What do you think is causing the error? What are contributing factors? (To be discussed and worked on in class.)


== Automating the delivery pipeline

Now that we have a working application that can be deployed to Kubernetes, we can automate the delivery pipeline. It's now time to start using Github Actions so that we can easily move changes into the cluster, without having to execute a lot of commands. 

We'll start with automated testing. As discussed in the DPBoK, we are continually evolving our systems, and as we make changes, we need the systems to keep their existing functionality.


=== Automated testing

In the node-svc directory there is a `test` directory, with a file in it called `test.js`. Have a look at it. It is a very basic automated test that checks that `server.js` operates and successfully responds to a simple GET. 

You can run the test by simply typing 
`npm test`. Try it. 

=== Continuous delivery 

In your directory, you will also find a directory called `.github,` with a subdirectory `workflows` and a file `GKE.yml`. The file is a Github Actions script. Have a look at it. It's a basic pipeline, including: 

* testing the application
* building the Docker image
* pushing the Docker image to the Google Container Registry (GCR). 
* deploying from the GCR to Kubernetes

Your final task for this lab is to configure your Github repository to run the pipeline. See https://github.com/GoogleCloudPlatform/github-actions/tree/master/example-workflows/gke[this page.]

As the page indicates, you need to enable the appropriate APIs, create a service account, download the JSON service account key and configure the appropriate secrets in the repository Settings:

* GKE_PROJECT
* GKE_SA_KEY

NOTE: Keep the service account key in a secure location, such as a password manager. It is equivalent to an ssh private key. Once you put it into Github, you cannot retrieve it. 

Once you have this configured, the pipeline should run whenever you make a change to server.js. Try changing the output of `app.get('/0?'..` as suggested in the code comments.

=== Submitting evidence

Take a screenshot of the pipeline page showing that it has successfully run all steps, and a screen shot showing a /20 or greater call to the microservices running on the Kubernetes cluster. 

=== Destroy the cluster

To destroy the Kubernetes cluster, run the following command inside `kubernetes/terraform` directory:

[source,bash]
----
$ ~/bin/terraform destroy
----


