= Lab 02 (Technical) IT Infrastructure

== Adding a VM

It's a rare production system that only has one virtual machine, or container. Therefore we will start early with a simple two-node system. 

NOTE: Rather than using a two-tier system with an application and database node, this initial system uses a single microservice that can both request and reply to API calls, and can easily interoperate with itself. For now, each node will have one installation of this service. 


[source,bash]
----
$ gcloud compute instances create  node-svc-01\
    --image-family ubuntu-minimal-2004-lts  \
    --image-project ubuntu-os-cloud \
    --boot-disk-size 10GB \
    --machine-type f1-micro

$ gcloud compute instances create  node-svc-02\
    --image-family ubuntu-minimal-2004-lts  \
    --image-project ubuntu-os-cloud \
    --boot-disk-size 10GB \
    --machine-type f1-micro

$ NODE_IP_01=$(gcloud --format="value(networkInterfaces[0].accessConfigs[0].natIP)" compute instances describe node-svc-01)

$ NODE_IP_02=$(gcloud --format="value(networkInterfaces[0].accessConfigs[0].natIP)" compute instances describe node-svc-01)

$ ssh node-user@${NODE_IP_01}
----

== Terraform

* Before starting, review this article on environment variables. https://phoenixts.com/blog/environment-variables-in-linux. If you do not understand, ask. 
* Create a new Github repo on your account titled Lab02-<your St. Thomas ID>. That is, if your St. Thomas email is sala0001@stthomas.edu, name it Lab02-sala0001. Include a .gitignore file configured for Terraform. 
* Clone it down to the Google Cloud Shell (Request assistance if you need it with Github). 

IMPORTANT: It is ESSENTIAL to create a .gitignore file properly configured for Terraform. For further information on .gitignore see https://git-scm.com/docs/gitignore. The required contents follow. 

.gitignore contents:
....
#  Local .terraform directories
**/.terraform/*

# .tfstate files
*.tfstate
.tfstate.

# .tfvars files
*.tfvars

....

=== Troubleshooting 

If you get 

....
Error refreshing state: state snapshot was created by Terraform v0.12.8, which is newer than current v0.12.2; upgrade to Terraform v0.12.8 or greater to work with this state
....

execute 
`rm -rf terraform.tfstate`
`terraform init`

